# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views\department.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Department(object):
    def setupUi(self, Department):
        Department.setObjectName("Department")
        Department.resize(497, 327)
        self.verticalLayout = QtWidgets.QVBoxLayout(Department)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_search = QtWidgets.QWidget(Department)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel_search.sizePolicy().hasHeightForWidth())
        self.panel_search.setSizePolicy(sizePolicy)
        self.panel_search.setStyleSheet("backgruound: white;")
        self.panel_search.setObjectName("panel_search")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.panel_search)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_title = QtWidgets.QLabel(self.panel_search)
        self.lbl_title.setStyleSheet("font-size: 16px;")
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_2.addWidget(self.lbl_title)
        self.lbl_name = QtWidgets.QLabel(self.panel_search)
        self.lbl_name.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_name.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout_2.addWidget(self.lbl_name)
        self.edt_name = QtWidgets.QLineEdit(self.panel_search)
        self.edt_name.setMinimumSize(QtCore.QSize(0, 30))
        self.edt_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edt_name.setObjectName("edt_name")
        self.verticalLayout_2.addWidget(self.edt_name)
        self.btn_search = QtWidgets.QPushButton(self.panel_search)
        self.btn_search.setMinimumSize(QtCore.QSize(0, 29))
        self.btn_search.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_search.setObjectName("btn_search")
        self.verticalLayout_2.addWidget(self.btn_search)
        self.verticalLayout.addWidget(self.panel_search)
        self.panel_table = QtWidgets.QWidget(Department)
        self.panel_table.setStyleSheet("backgruound: white;")
        self.panel_table.setObjectName("panel_table")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.panel_table)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_add = QtWidgets.QPushButton(self.panel_table)
        self.btn_add.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_add.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout_3.addWidget(self.btn_add)
        self.table_department = QtWidgets.QTableWidget(self.panel_table)
        self.table_department.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_department.setAlternatingRowColors(True)
        self.table_department.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_department.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_department.setProperty("horizontalHeaderSetSectionResizeMode", 3)
        self.table_department.setObjectName("table_department")
        self.table_department.setColumnCount(4)
        self.table_department.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_department.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_department.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_department.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_department.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.table_department)
        self.verticalLayout.addWidget(self.panel_table)

        self.retranslateUi(Department)
        QtCore.QMetaObject.connectSlotsByName(Department)

    def retranslateUi(self, Department):
        _translate = QtCore.QCoreApplication.translate
        Department.setWindowTitle(_translate("Department", "Form"))
        self.lbl_title.setText(_translate("Department", "LISTAGEM DE DEPARTAMENTO"))
        self.lbl_name.setText(_translate("Department", "Nome"))
        self.btn_search.setText(_translate("Department", "Pesquisar"))
        self.btn_add.setText(_translate("Department", "Adicionar"))
        item = self.table_department.horizontalHeaderItem(0)
        item.setText(_translate("Department", "Código"))
        item = self.table_department.horizontalHeaderItem(1)
        item.setText(_translate("Department", "Nome"))
        item = self.table_department.horizontalHeaderItem(2)
        item.setText(_translate("Department", "Modificado em"))
        item = self.table_department.horizontalHeaderItem(3)
        item.setText(_translate("Department", "Ativo"))
