# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 321)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.body = QtWidgets.QWidget(self.centralwidget)
        self.body.setStyleSheet("background: white;")
        self.body.setObjectName("body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addWidget(self.body)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 21))
        self.menubar.setObjectName("menubar")
        self.menuCadastros = QtWidgets.QMenu(self.menubar)
        self.menuCadastros.setObjectName("menuCadastros")
        MainWindow.setMenuBar(self.menubar)
        self.actionEstado_Civil = QtWidgets.QAction(MainWindow)
        self.actionEstado_Civil.setObjectName("actionEstado_Civil")
        self.actionDepartamento = QtWidgets.QAction(MainWindow)
        self.actionDepartamento.setObjectName("actionDepartamento")
        self.actionFuncion_rio = QtWidgets.QAction(MainWindow)
        self.actionFuncion_rio.setObjectName("actionFuncion_rio")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.menuCadastros.addAction(self.actionEstado_Civil)
        self.menuCadastros.addAction(self.actionDepartamento)
        self.menuCadastros.addAction(self.actionFuncion_rio)
        self.menuCadastros.addSeparator()
        self.menuCadastros.addAction(self.actionSair)
        self.menubar.addAction(self.menuCadastros.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuCadastros.setTitle(_translate("MainWindow", "Cadastros"))
        self.actionEstado_Civil.setText(_translate("MainWindow", "Estado Civil"))
        self.actionDepartamento.setText(_translate("MainWindow", "Departamento"))
        self.actionFuncion_rio.setText(_translate("MainWindow", "Funcionário"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
