# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views\marital_status.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MaritalStatus(object):
    def setupUi(self, MaritalStatus):
        MaritalStatus.setObjectName("MaritalStatus")
        MaritalStatus.resize(487, 327)
        self.verticalLayout = QtWidgets.QVBoxLayout(MaritalStatus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_search = QtWidgets.QWidget(MaritalStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel_search.sizePolicy().hasHeightForWidth())
        self.panel_search.setSizePolicy(sizePolicy)
        self.panel_search.setStyleSheet("backgruound: white;")
        self.panel_search.setObjectName("panel_search")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.panel_search)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_title = QtWidgets.QLabel(self.panel_search)
        self.lbl_title.setStyleSheet("font-size: 16px;")
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_2.addWidget(self.lbl_title)
        self.lbl_name = QtWidgets.QLabel(self.panel_search)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout_2.addWidget(self.lbl_name)
        self.edt_name = QtWidgets.QLineEdit(self.panel_search)
        self.edt_name.setObjectName("edt_name")
        self.verticalLayout_2.addWidget(self.edt_name)
        self.btn_search = QtWidgets.QPushButton(self.panel_search)
        self.btn_search.setObjectName("btn_search")
        self.verticalLayout_2.addWidget(self.btn_search)
        self.verticalLayout.addWidget(self.panel_search)
        self.panel_table = QtWidgets.QWidget(MaritalStatus)
        self.panel_table.setStyleSheet("backgruound: white;")
        self.panel_table.setObjectName("panel_table")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.panel_table)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_add = QtWidgets.QPushButton(self.panel_table)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout_3.addWidget(self.btn_add)
        self.table_marital_status = QtWidgets.QTableWidget(self.panel_table)
        self.table_marital_status.setObjectName("table_marital_status")
        self.table_marital_status.setColumnCount(2)
        self.table_marital_status.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_marital_status.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_marital_status.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.table_marital_status)
        self.verticalLayout.addWidget(self.panel_table)

        self.retranslateUi(MaritalStatus)
        QtCore.QMetaObject.connectSlotsByName(MaritalStatus)

    def retranslateUi(self, MaritalStatus):
        _translate = QtCore.QCoreApplication.translate
        MaritalStatus.setWindowTitle(_translate("MaritalStatus", "Form"))
        self.lbl_title.setText(_translate("MaritalStatus", "LISTAGEM DE ESTADO CIVIL"))
        self.lbl_name.setText(_translate("MaritalStatus", "Nome"))
        self.btn_search.setText(_translate("MaritalStatus", "Pesquisar"))
        self.btn_add.setText(_translate("MaritalStatus", "Adicionar"))
        item = self.table_marital_status.horizontalHeaderItem(0)
        item.setText(_translate("MaritalStatus", "Código"))
        item = self.table_marital_status.horizontalHeaderItem(1)
        item.setText(_translate("MaritalStatus", "Nome"))
