# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views\marital_status_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MaritalStatusItem(object):
    def setupUi(self, MaritalStatusItem):
        MaritalStatusItem.setObjectName("MaritalStatusItem")
        MaritalStatusItem.resize(400, 142)
        self.verticalLayout = QtWidgets.QVBoxLayout(MaritalStatusItem)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(MaritalStatusItem)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font-size: 16px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(MaritalStatusItem)
        QtCore.QMetaObject.connectSlotsByName(MaritalStatusItem)

    def retranslateUi(self, MaritalStatusItem):
        _translate = QtCore.QCoreApplication.translate
        MaritalStatusItem.setWindowTitle(_translate("MaritalStatusItem", "Dialog"))
        self.label_2.setText(_translate("MaritalStatusItem", "CADASTRO DE ESTADO CIVIL"))
        self.label.setText(_translate("MaritalStatusItem", "Nome"))
        self.pushButton.setText(_translate("MaritalStatusItem", "PushButton"))
